### ISSUE TITLE
AttributeError: "'loss'"

### ISSUE THREAD

**Issue by QUEST2179** [seoklab/ComMat#1]
Could you please help? Thanks!

Traceback (most recent call last):
  File "/home/work/project/antibody/ComMat-main/scripts/inference.py", line 125, in <module>
    hu_config.loss.seed_size = args.test_seed_size
  File "/home/work/miniconda/envs/gpu9/lib/python3.9/site-packages/ml_collections/config_dict/config_dict.py", line 829, in __getattr__
    raise AttributeError(e)
AttributeError: "'loss'"

**Comment by marcbianciotto** [comment]
Hi there, I face the exact same error. 
Any help would be welcome.

Best,

M.
